### PR TITLE
Reorderable posts

### PR DESCRIPTION
**Pull request by Ricefrog**
## Describe your changes
- User can click on the drag icon and move the mouse to reorder posts.
- While the post is being dragged a "shadow post" will appear where the post will land when the user lets go of the mouse.
- Users must click on the actual icon to be able to drag posts rather than having the entire blue element be clickable. I made this change because the post would jump to the user's cursor position on click which can be unexpected. This can be fixed with some algebra in the future. 
- There is a new object store in IDB that holds an array of post IDs indicating the order in which the posts should appear. It is kept in sync with changes the user makes to ordering.
- Reordering is synced with the DB on mouse up.
- If the ordering array needs to be changed due to a deleted post it is done on post deletion rather than waiting for the Save button to be clicked.

https://user-images.githubusercontent.com/48808721/204177003-e4ee4928-2d22-4f69-bbef-a2fa4ee15759.mp4

## Issue ticket number and link
Issue #15 

## Checklist before requesting a review
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by Ricefrog** [comment]
TODO: Get unit tests working again.

**Review by Roland-Wen — CHANGES_REQUESTED** [review]
After I dragged an image post to a new position and then edited the caption content, the post would go back to its original position. This happened when I clicked on "Update" of the image post popup.

https://user-images.githubusercontent.com/78676749/204179041-1029d6ed-f670-4540-bace-65c6b8f3ddc0.mp4

**Comment by Ricefrog** [comment]
https://user-images.githubusercontent.com/48808721/204190324-62a7afdf-bab3-4ee0-86c7-e5a788f2df04.mp4

Bug seems to be fixed. No issues with adding/removing images from a post or editing text posts either.

**Review by Roland-Wen — APPROVED** [review]
Great work! Looks good now

**Review by navidboloorian — APPROVED** [review]
Looks great! Don't forget to add/fix tests

**Pull request merged**
