### PR TITLE
Finished HTML and CSS for main page

### LINKED ISSUE #10: Create main.html boilerplate
- Add user section at top
- Create dummy posts div to store posts later
    - Posts should be of class "post"
---
https://www.figma.com/file/04WKQVpSqwjka7M6g4IZOX/CSE-110-Group-Project?node-id=0%3A1

### LINKED ISSUE #11: Create main.css for main.html styling
- Add relevant colors from figma
- Center elements on page
    - Consider using CSS grid or flex
- Contents should have a max width of 800px
- Gaps between posts are precisely 20px
- Buttons should be fixed to bottom right corner
---
- Ari and Joseph
    - User details header (top of page) 
    - Fixed buttons on bottom right corner
        - Create assets for edit, add, and save
- Jiaying and Zixian 
    - Posts
        - Use dummy data
        - Make image post class and text post class
        - Style according to figma 
        - Add draggable and delete icons, we'll hide these later with javascript
- Ryan
    - Create new post block at the bottom of the screen
    - Consists of two clickable portions
---
https://www.figma.com/file/04WKQVpSqwjka7M6g4IZOX/CSE-110-Group-Project?node-id=0%3A1

### PR DESCRIPTION
**Pull request by navidboloorian**
## Describe your changes
- Added HTML boilerplate
- Added dummy data to style temporarily before it becomes generated by JS
- Styled posts, navbar, and buttons
- Styles now match with figma file
- To review, compare with figma file and make sure everything displays ok at various window sizes

## Issue ticket number and link
- #11 
- #10 

## Checklist before requesting a review
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by Roland-Wen** [comment]
The display is off when screen length is greater than width (tested with dimensions of Samsung Galaxy S8+ from dev-tools). Everything else looks great.

**Comment by navidboloorian** [comment]
> The display is off when screen length is greater than width (tested with dimensions of Samsung Galaxy S8+ from dev-tools). Everything else looks great.

Good note, added media queries and some grid adjustments to fix the display. Let me know if that addresses everything

**Review by Roland-Wen — APPROVED** [review]
Looks good now!

**Review by zixianwang2022 — APPROVED** [review]
Looks pretty good

**Pull request merged**
