### PR TITLE
Image post CRU

### PR DESCRIPTION
**Pull request by navidboloorian**
## Describe your changes
- Implemented creation of image posts
- Image posts also display on main.html by making calls to db
- Implemented update for image posts
- Disallowed empty image posts on update and on creation
unplugged_image_posts

## Issue ticket number and link
#35 
#38 
#17 

## Checklist before requesting a review
- [x] I have performed a self-review of my code

### CODE REVIEW

**Review by zixianwang2022 — COMMENTED** [review]
截屏2022-11-23 00 29 30

When I add an image post, the popup has some margin left blank.

**Review by zixianwang2022 — APPROVED** [review]
Everything else looks great to me

**Comment by navidboloorian** [comment]
Good catch, seems to have been a chrome issue as it was displaying properly on Firefox. Problem is fixed

**Review by Ricefrog — APPROVED** [review]
LGTM

**Pull request merged**
