### PR TITLE
Image full view popup

### PR DESCRIPTION
**Pull request by Jiy014**
## Describe your changes

1. Now we can click on the image from image posts
2. A larger view of the image will pop up and the caption will be on the side
3. The captions are scrollable
4. The size of the pop-up window will be based on the height of the image.

## Issue ticket number and link
[Issue 46](https://github.com/cse110-fa22-group20/cse110-fa22-group20/issues/46)

https://user-images.githubusercontent.com/114895123/205308794-52fed636-1fc0-424c-98f8-8a5c7b4a32ec.mp4

## Checklist before requesting a review
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by Jiy014** [comment]
> ## Describe your changes
> 1. Now we can click on the image from image posts
> 2. A larger view of the image will pop up and the caption will be on the side
> 3. The captions are scrollable
> 4. The size of the pop-up window will be based on the height of the image.
> 
> ## Issue ticket number and link
> [Issue 46](https://github.com/cse110-fa22-group20/cse110-fa22-group20/issues/46)
> 
> ## Checklist before requesting a review
> * [x]  I have performed a self-review of my code

**Comment by navidboloorian** [comment]
image_pop
Made some changes so that posts w/o captions don't show an empty bar on the right. Increased the width of images and made the caption box scale with the image. It's not perfect but it's the best I could do in the 30 mins or so I had.

**Review by Roland-Wen — CHANGES_REQUESTED** [review]
There're 2 scrollbars (Chrome).
image

**Comment by Jiy014** [comment]
> There're 2 scrollbars (Chrome). image

Thanks for letting me know. On my Chrome it seems okay, and also the scrollbar looks different on mine. I tried to fix it so can you try again with the new commit? Also, do you mind checking the styling of the caption on your Chrome?

**Review by Ricefrog — APPROVED** [review]
Looks great! I'm on Firefox and did not encounter the double scrollbar issue.

**Review by Roland-Wen — COMMENTED** [review]
The double scrollbars is still there, but it might be an issue on my end only.
image
Also, when there's a really long word in the caption, part of it got cut off. 

https://user-images.githubusercontent.com/78676749/205509657-dd88717b-c471-48c9-bfa8-9e449864dd13.mp4

**Comment by Jiy014** [comment]
> The double scrollbars is still there, but it might be an issue on my end only. image Also, when there's a really long word in the caption, part of it got cut off.
> 
>  2022-12-04.10-50-42.mp4

For the really long caption word, I was assuming there isn't a word that's this long. If there is a paragraph it should change to the next line properly. 

I changed the caption to the x-axis scrollable, so it should be working now without interfering with the regular paragraph.

**Review by Roland-Wen — APPROVED** [review]
Looks good now!

**Pull request merged**
