### PR TITLE
New userhtml functional staging

### PR DESCRIPTION
**Pull request by Roland-Wen**
## Describe your changes
- Made the user able to input name, description, and image
- Stored those items into indexedDB
- User name must be at least 1 character long
- Testing does NOT work since the browser uses "export{...}" while jest uses "exports. ... = ..."

https://user-images.githubusercontent.com/78676749/201748114-f2d51b9f-f82e-4fcc-b686-c0b1495d19f8.mp4

## Issue ticket number and link
- #13 

## Checklist before requesting a review
- [x] I have performed a self-review of my code

### CODE REVIEW

**Review by navidboloorian — APPROVED** [review]
LGTM! Awesome work! Make sure to resolve conflicts before merging but otherwise excellent :)

**Comment by Ricefrog** [comment]
Solid work and looks great!

**Comment by Ricefrog** [comment]
Solid work and looks great!

**Review by Ricefrog — APPROVED** [review]
Solid work and looks great!

**Pull request merged**
