### PR TITLE
Text post edit nodb staging

### LINKED ISSUE #28: Read information from DB to populate main page posts and user data
- Fill IndexedDB with dummy data for both posts and user information (more details in db.js)
- Generate posts from the IndexedDB information 
- Might want to utilize shadow DOM
- Use "getAllPosts" and "getDetails" from db.js

### LINKED ISSUE #34: Week 8: When in edit mode, clicking on text post renders a text area and submit button

### PR DESCRIPTION
**Pull request by Ricefrog**
## Describe your changes
- Clicking "Edit" will add drag/delete icons to all posts.
- In Edit-Mode, clicking on the text of a post makes it editable. 
- Clicking submit will change the text of the post and make it uneditable again. The `state` object is updated in the JS but the DB is not updated. 
- If a user attempts to submit an empty post the text content of the editable div will be set to "Posts cannot be empty." and nothing will be submitted.
- In Edit-Mode, clicking the "Save" button will switch the page back to the default mode.
- The "Save" button is hidden while editing a post.
- Multiple posts cannot be edited at the same time. After the user is done editing a post, they will then be able to click on other posts to edit them.

Note: In the video, there is a point where it looks like an extra newline is added to the text. I will try to find a fix before this pull request is closed.

https://user-images.githubusercontent.com/48808721/202835629-0e28b9fd-b5c8-49b7-b0cb-2892a050b70b.mp4

## Issue ticket number and link
Issue #34 

## Checklist before requesting a review
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by navidboloorian** [comment]
Looks pretty awesome, love the music as well. Can you hide the Add button when edit is activated? Also add like 5px of padding to the submit button

**Review by Roland-Wen — APPROVED** [review]
Great work! Really like the idea of using a "state" variable.

**Review by navidboloorian — CHANGES_REQUESTED** [review]
Working on some bug fixes with display issues. Thinking about maybe ditching the in place editing, might be more of a hassle than it's worth.

**Comment by navidboloorian** [comment]
unplugged_edit_demo

**Review by navidboloorian — APPROVED** [review]
Removing 'request for changes'

**Comment by Roland-Wen** [comment]
Seems like the popup would show up even if the user clicked on drag or delete. Not sure if that'll be a problem.

https://user-images.githubusercontent.com/78676749/203241512-763e14a4-7b33-41b8-b816-4e0c81768782.mp4

**Comment by navidboloorian** [comment]
Good catch, fixed

**Pull request merged**
