### PR TITLE
Text input post style

### PR DESCRIPTION
**Pull request by Jiy014**
## Describe your changes
Text post style update:
1. Darken the background
2. Looks like Figma
3. Closing post

## Issue ticket number and link
Number 27
https://github.com/cse110-fa22-group20/cse110-fa22-group20/issues/27

## Checklist before requesting a review
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by Roland-Wen** [comment]
Text was not added to db (not sure if this is intended).
After clicking the close post button, the user can no longer do anything (see video). Post form does not disappear after clicking submit (not sure if this is intended).
The darkened background is kind of off when scrolling down (see video).

https://user-images.githubusercontent.com/78676749/202590804-c23b0342-6551-4313-bc85-04f048b2b1cc.mp4

**Review by navidboloorian — CHANGES_REQUESTED** [review]
Agree with @Roland-Wen, take a look at my PR for image popup for help on fixing the scrolling issue and small tweaks like background color

**Comment by navidboloorian** [comment]
> Text was not added to db (not sure if this is intended). After clicking the close post button, the user can no longer do anything (see video). Post form does not disappear after clicking submit (not sure if this is intended). The darkened background is kind of off when scrolling down (see video).
> 
>  2022-11-17.16-43-25_Trim.mp4

Not necessary to import text into db though--Koa handled that in his task--rest is accurate.

**Comment by navidboloorian** [comment]
Remade the text popup
Added some quality of life changes as well. For example, upon clicking add post it will scroll to the bottom of the page. 

unplugged_add_text_post

**Review by navidboloorian — APPROVED** [review]
Approving just to remove my negative review, still need 2 more people

**Review by Roland-Wen — APPROVED** [review]
LGTM

**Pull request merged**
